GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcnJ5IiwiaWQiOiI2MmYxMjE5NDlkYTRkYjJhNzdlYzJmYTEiLCJpYXQiOjE2NjA0ODM1NjF9.ILPVKjYy9QzGI7p8gGXOA1hi-rx-_dozQAKxCIV0kCI
###
POST http://localhost:3001/api/orders
Content-Type: application/json

{
    "user": "635ac046b01737e727fb4b42",
    "orderDate": "28/03/12",
    "orderStatus": "Delivery In Progress",
    "products": ["635abd38b01737e727fb4b38", "635c3dc47d63de93d0c7f798"],
    "deliveryDate": "28/04/12"
}
###
POST https://support-local.herokuapp.com/api/products
Content-Type: application/json

{
  "name": "Coreela Padded Pleated Crop Top",
  "price": 45,
  "specialPrice": 40,
  "category": "Women's Apparel",
  "rating": 4,
  "imgUrl": "assets/img/products/flaredress.png",
  "numberSold": 7,
  "productDesc": "A brunch-to-dinner mainstay to have in your rotation. Made of textured linen, this dress features a fit & flare silhouette and a square neckline. Puffed at the sleeves to channel a romantic air. Comes with functional side pockets and a back zip closure.",
  "productSpec": ["Textured Linen", "Machine Washable"],
  "merchant": "636a8f4b7d63de93d0c7f95a"
}
###
POST https://support-local.herokuapp.com/api/merchants
Content-Type: application/json

{
  "name": "Love Bonito",
  "aboutUs": "Designed in Singapore, our styles are made with care, ensuring quality and value through thoughtful yet functional design details. Our in-house designers remain committed to perfecting the Asian fit for the everyday modern Asian woman.",
  "imgUrl": "assets/img/merchants/love.png",
  "location": "313 Orchard Rd, #02 - 16 / 21, Singapore 238895",
  "coord": "1.3012697801439204, 103.8387671",
  "phoneNo": "90612330",
  "email": "hello@lovebonito.com",
  "lastOnline": 10,
}
###
DELETE  http://localhost:3001/api/products/636120625efd11809b18c9a6
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcnJ5IiwiaWQiOiI2MmYxMjE5NDlkYTRkYjJhNzdlYzJmYTEiLCJpYXQiOjE2NjA0ODM1NjF9.ILPVKjYy9QzGI7p8gGXOA1hi-rx-_dozQAKxCIV0kCI
###

PATCH http://localhost:3001/api/users/635ac046b01737e727fb4b42
Content-Type: application/json

{
  "orderDetails": ["636924d7760a582d6bd259b0"]
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Barry",
  "password": "salainen"
}
###
GET https://support-local.herokuapp.com/api/orders
Content-Type: application/json

