GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcnJ5IiwiaWQiOiI2MmYxMjE5NDlkYTRkYjJhNzdlYzJmYTEiLCJpYXQiOjE2NjA0ODM1NjF9.ILPVKjYy9QzGI7p8gGXOA1hi-rx-_dozQAKxCIV0kCI
###
POST http://localhost:3001/api/orders
Content-Type: application/json

{
    "user": "635ac046b01737e727fb4b42",
    "orderDate": "28/03/12",
    "orderStatus": "Delivery In Progress",
    "products": ["635abd38b01737e727fb4b38", "635c3dc47d63de93d0c7f798"],
    "deliveryDate": "28/04/12"
}
###
POST https://support-local.herokuapp.com/api/products
Content-Type: application/json

{
  "name": "Heritage Ear Jacket",
  "price": 488,
  "specialPrice": 460,
  "category": "Women's Apparel",
  "rating": 4,
  "imgUrl": "assets/img/products/EarJacket.png",
  "numberSold": 1,
  "productDesc": "Built with the modern women in mind, our Heritage Ear Jackets can be worn with just the studs, with the jackets, mismatched or the jackets with your own solitaire.",
  "productSpec": ["Clear Gems"],
  "merchant": "636a15717d63de93d0c7f931"
}
###
POST https://support-local.herokuapp.com/api/merchants
Content-Type: application/json

{
  "name": "Carrie K.",
  "aboutUs": "Carrie K. creates meaningful and versatile jewellery that lets you bring your story to life. Passionate about story-telling, we translate your journeys into meaningful and modular jewellery that transforms from simple everyday wear to statement pieces for special days. We exist to bring people together through these thoughtful conversation starters, and nurture a positive community through meaningful interactions.",
  "imgUrl": "assets/img/merchants/carrie.png",
  "location": "111 Middle Rd, #02-02 National Design Centre, Singapore 188969",
  "coord": "1.3003785363064932, 103.85275606347334",
  "phoneNo": "90612880",
  "email": "contact@carriekrocks.com",
  "lastOnline": 18,
}
###
DELETE  http://localhost:3001/api/products/636120625efd11809b18c9a6
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcnJ5IiwiaWQiOiI2MmYxMjE5NDlkYTRkYjJhNzdlYzJmYTEiLCJpYXQiOjE2NjA0ODM1NjF9.ILPVKjYy9QzGI7p8gGXOA1hi-rx-_dozQAKxCIV0kCI
###

PATCH http://localhost:3001/api/users/635ac046b01737e727fb4b42
Content-Type: application/json

{
  "orderDetails": ["636924d7760a582d6bd259b0"]
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Barry",
  "password": "salainen"
}
###
GET https://support-local.herokuapp.com/api/orders
Content-Type: application/json

